apiVersion: apps/v1
kind: Deployment
metadata: 
   name: nginx-deployment
   labels: 
      app: nginx
spec: 
   selectors: 
      name: nginx
   replicas: 2
   templates: 
      metadata:
          labels: 
            app: nginx
      spec:
          containers:
          - name: nginx
            image: nginx:1.14.2
            ports:
            - containerPort: 80 
              name: nginxport
               
    